### ISSUE TITLE
Animated Sprites

### ISSUE THREAD

**Issue by WestRodri** [HalfstarDev/matchanovel#6]
You don't have to break it down fully , you can just point me in the right direction. 
Is this able to have animated sprites for characters blinking or slightly swaying? If not
how would you recommend going about this? 

Also maybe having effects on said sprites, like changing the saturation or blurring. 

I'm an intermediate programmer but new to defold so feel free to be technical. I appreciate your time reading this!

**Comment by HalfstarDev** [comment]
I'm currently reworking the sprite system, with a system that allows animations like blinking and swaying (and also sprites with multiple layers), which I plan to add to the next major release. As I want to finish the visual novel I'm currently working on first, so I can properly test the new features, the next release will take at least a few months. If somebody wanted to implement that manually before, they'd have to edit sprites.gui_script, but as I plan to remove the objects "sprites" and "background", and add a new object "scene" that handles both, I would advise against rewriting it now.

About effects, currently I'm planning to add changing the brightness, tint, and transparency of sprites. The basic sprite shader for Defold does not allow changing the saturation, but I have tested a custom shader to change saturation and hue. But with how the material system in Defold works at the moment, I'll have to do some more work so that changing the saturation of only one sprite is possible. This will not be ready for the next release, but something I want to do later. Blur would be even harder, so when I'm done with a custom shader, others can try to add a blur feature, but I'm not planning to make one at the moment.

**Comment by WestRodri** [comment]
I appreciate the thoughtful response! I'm going to start developing my own visual novel and I'm really glad you made Match Novel. It helps me have a good baseline from where to start with Defold. I'll be trying to implement the animated sprites but look forward to how you end up doing it with scenes. 

I also know a bit shader language and will be trying that too. I'll be watching the project! Thanks again, I look forward to the next update and I hope you have a great day!!
